# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.1

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - apt-get update && apt-get install -y postgresql-client
          - yarn
          - yarn createDB
          - yarn pgRestore
          - yarn test
          
        services:
          - redis
          - postgres

 
definitions:
  services:
    redis:
      image: redis
    postgres: 
      image: postgres 
        