version: '3.4'
services:
 node-app:
    build: 
      context: ./ 
      dockerfile: dockerfile.test
    network_mode: host
    ports:
      - "3009:3009"
    depends_on:
        - redis
        - postgres
    #command: bash -c 'yarn createDB  && yarn pgRestore && yarn test'
    #container_name: node_container 
 redis:
        image: redis
        ports:
          - "6379"  
 postgres:
        image: postgres:latest
        ports:
          - "5432"
        environment:
         PGHOST: db
         POSTGRES_PASSWORD: abc123
         POSTGRES_USER: postgres
         POSTGRES_DB: postgres
        
 
            
          