- name: Traffic to Badge
 # You may pin to the exact commit or the version.
  # uses: yi-Xu-0100/traffic-to-badge@6e7656202ad370afe7e80465c32ee367324ab4fc
  uses: yi-Xu-0100/traffic-to-badge@v1.4.0
  with:
    # Set up a personal access token to obtain the secret repository traffic data.

    my_token: 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
    # Set up a list of repositories to get. Only when github.repository with setting into first item, it can be correct to be current repository name.

    static_list: # optional, default is ${{ github.repository }}
    # If empty traffic data will be backed up to the branch named traffic.

    traffic_branch: # optional, default is traffic
    # Set a hex or named color value for the views badge background.

    views_color: # optional, default is brightgreen
    # Set a hex or named color value for the clones badge background.

    clones_color: # optional, default is brightgreen
    # Set a hex or named color value for the views per week badge background.

    views_week_color: # optional, default is brightgreen
    # Set a hex or named color value for the clones per week badge background.

    clones_week_color: # optional, default is brightgreen
    # Set a hex or named color value for the total views badge background.

    total_views_color: # optional, default is brightgreen
    # Set a hex or named color value for the total clones badge background.

    total_clones_color: # optional, default is brightgreen
    # Set a hex or named color value for the total views per week badge background.

    total_views_week_color: # optional, default is brightgreen
    # Set a hex or named color value for the total clones per week badge background.

    total_clones_week_color: # optional, default is brightgreen
    # Insert a named logo or simple-icon to the left of the label.

    logo: # optional, default is github
    # Set a year number for license year beginning. If empty, it will no beginning year.

    year: # optional
